In [1]:
import sys
import os

module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path + "/src/simulations_v2")

from stochastic_simulation import StochasticSimulation

In [2]:
import numpy as np

params = {
    'max_time_exposed': 4,
    'exposed_time_function': (lambda n: np.random.multinomial(n, [1/4]*4)),
    
    'max_time_pre_ID': 2,
    'pre_ID_time_function': (lambda n: np.random.multinomial(n, [1/2]*2)),
    
    'max_time_ID': 14,
    'ID_time_function': (lambda n: np.random.multinomial(n, [1/14]*14)),
    
    'sample_QI_exit_function': (lambda n: np.random.binomial(n, 0.05)),
    'sample_QS_exit_function': (lambda n: np.random.binomial(n, 0.3)),
    
    'exposed_infection_p': 0.05,
    'expected_contacts_per_day': 3,
    
    'days_between_tests': 1,
    'test_population_fraction': 1/6,
    'test_protocol_QFNR': 0.1,
    'test_protocol_QFPR': 0.005,
    
    'perform_contact_tracing': False,
    'contact_tracing_constant': None,
    
    'pre_ID_state': 'detectable',
    
    'population_size': 1000,
    'initial_E_count': 10,
    'initial_pre_ID_count': 10,
    'initial_ID_count': 0
}

sim = StochasticSimulation(params)

In [8]:
sim.get_current_state_vector()

array([947,   1,   4,   1,   9,   8,  12,   4,   0,   3,   0,   0,   2,
         1,   0,   2,   1,   0,   2,   0,   0,   3,   0,   0])

In [5]:
sim.step()

In [6]:
sim.sim_df

Empty DataFrame
Columns: [S, QS, QI, R, E_0, E_1, E_2, E_3, pre_ID_0, pre_ID_1, ID_0, ID_1, ID_2, ID_3, ID_4, ID_5, ID_6, ID_7, ID_8, ID_9, ID_10, ID_11, ID_12, ID_13]
Index: []

[0 rows x 24 columns]

In [9]:
data = sim.get_current_state_vector()
labels = sim.get_state_vector_labels()

In [27]:
sim.E

array([12, 11,  4,  4])

In [28]:
labels

['S',
 'QS',
 'QI',
 'R',
 'E_0',
 'E_1',
 'E_2',
 'E_3',
 'pre_ID_0',
 'pre_ID_1',
 'ID_0',
 'ID_1',
 'ID_2',
 'ID_3',
 'ID_4',
 'ID_5',
 'ID_6',
 'ID_7',
 'ID_8',
 'ID_9',
 'ID_10',
 'ID_11',
 'ID_12',
 'ID_13']

In [17]:
labels

['S',
 'QS',
 'QI',
 'R',
 'E_0',
 'E_1',
 'E_2',
 'E_3',
 'pre_ID_0',
 'pre_ID_1',
 'ID_0',
 'ID_1',
 'ID_2',
 'ID_3',
 'ID_4',
 'ID_5',
 'ID_6',
 'ID_7',
 'ID_8',
 'ID_9',
 'ID_10',
 'ID_11',
 'ID_12',
 'ID_13']

In [12]:
import pandas as pd
df = pd.DataFrame(columns=labels)
newdf = pd.DataFrame([data], columns=labels)

In [13]:
df

Empty DataFrame
Columns: [S, QS, QI, R, E_0, E_1, E_2, E_3, pre_ID_0, pre_ID_1, ID_0, ID_1, ID_2, ID_3, ID_4, ID_5, ID_6, ID_7, ID_8, ID_9, ID_10, ID_11, ID_12, ID_13]
Index: []

[0 rows x 24 columns]

In [14]:
newdf

S  QS  QI  R  E_0  E_1  E_2  E_3  pre_ID_0  pre_ID_1  ...    ID_4  ID_5  \
0  947   1   4  1    9    8   12    4         0         3  ...       0     2   

   ID_6  ID_7  ID_8  ID_9  ID_10  ID_11  ID_12  ID_13  
0     1     0     2     0      0      3      0      0  

[1 rows x 24 columns]

In [16]:
df.append(newdf)

S QS QI  R E_0 E_1 E_2 E_3 pre_ID_0 pre_ID_1  ...  ID_4 ID_5 ID_6 ID_7  \
0  947  1  4  1   9   8  12   4        0        3  ...     0    2    1    0   

  ID_8 ID_9 ID_10 ID_11 ID_12 ID_13  
0    2    0     0     3     0     0  

[1 rows x 24 columns]

In [11]:
df

S  QS  QI  R  E_0  E_1  E_2  E_3  pre_ID_0  pre_ID_1  ...    ID_4  ID_5  \
0  947   1   4  1    9    8   12    4         0         3  ...       0     2   

   ID_6  ID_7  ID_8  ID_9  ID_10  ID_11  ID_12  ID_13  
0     1     0     2     0      0      3      0      0  

[1 rows x 24 columns]

In [33]:
new_df = pd.DataFrame([data], columns=labels)
df.append(new_df)

S  QS  QI  R  E_0  E_1  E_2  E_3  pre_ID_0  pre_ID_1  ...    ID_4  ID_5  \
0  979   1   8  1   12   11    4    4         5         2  ...       0     2   
0  979   2   9  2   17   16   11    7         8         5  ...       1     1   

   ID_6  ID_7  ID_8  ID_9  ID_10  ID_11  ID_12  ID_13  
0     1     1     0     0      1      1      0      0  
0     2     0     0     2      2      0      2      0  

[2 rows x 24 columns]

In [30]:
df

S  QS  QI  R  E_0  E_1  E_2  E_3  pre_ID_0  pre_ID_1  ...    ID_4  ID_5  \
0  979   1   8  1   12   11    4    4         5         2  ...       0     2   

   ID_6  ID_7  ID_8  ID_9  ID_10  ID_11  ID_12  ID_13  
0     1     1     0     0      1      1      0      0  

[1 rows x 24 columns]

In [15]:
df.concat(pd.DataFrame(data))

AttributeError: 'DataFrame' object has no attribute 'concat'

In [13]:
import numpy as np

a = np.array([1,2,4])
b = [2]
c = np.array([1,3,3])
d = np.concatenate([a,b,c])

In [14]:
d

array([1, 2, 4, 2, 1, 3, 3])

In [20]:
np.random.binomial(10,0.3)

5

In [21]:
np.random.binomial(np.array([0,6,10]), 0.3)

array([0, 2, 2])

In [22]:
a = np.array([1,2,3])
b = np.array([2,2,2])
c = np.array([4,4,4])


In [24]:
d = c - a

In [25]:
d - b

array([ 1,  0, -1])

In [28]:
b = np.minimum(d,b)

In [29]:
b

array([2, 2, 1])

In [30]:
min(b)

1

In [32]:
np.random.choice([0,3,4], size=6, replace=False)

ValueError: Cannot take a larger sample than population when 'replace=False'